### ISSUE TITLE
Add explicit implementation of middleware interface?

### ISSUE THREAD

**Issue by elazar** [relayphp/Relay.Middleware#12]
Relay core has a [formalized interface](https://github.com/relayphp/Relay.Relay/commit/03981144d7cf06bb318c888f7c0865180ee423da) for middleware now. It would be nice if the middleware contained in this repo explicitly implemented this interface.

**Comment by elazar** [comment]
@pmjones Just FYI, I'm willing to submit a PR for this issue, but I'm assuming it will need to be based on a new 2.x branch, as has been done in Relay.Relay to resolve relayphp/Relay.Relay#17.

**Comment by pmjones** [comment]
/me ponders

Making these middleware pieces dependent on the MiddlewareInterace would mean making the package dependent on Relay proper.  I expect that non-Relay users will want to use the middleware, and at the same time avoid Relay itself.

Perhaps the thing to do in Relay 2.x is to split out the MiddlewareInterface to its own package.

@elazar @shadowhand @mindplay-dk thoughts?

**Comment by shadowhand** [comment]
@pmjones I would prefer that Relay depend on this package rather than the other way around.

**Comment by pmjones** [comment]
@shadowhand /me nods

I'd rather not have either depend on the other, frankly. However, I can see a case for completely removing the MiddlewareInterface from Relay itself, and then putting it either in its own package, or putting it in the Relay.Middleware package.

**Comment by elazar** [comment]
>  I can see a case for completely removing the MiddlewareInterface from Relay itself, and then ... putting it in the Relay.Middleware package.

:+1:

**Comment by shadowhand** [comment]
@pmjones ping?

**Comment by pmjones** [comment]
Coming back around to this. I think the right thing to do, esp. for Relay 2.x, is to create a Relay.MiddlewareInterface package, on which _both_ Relay.Relay 2.x _and_ Relay.Middleware 2.x can both depend.

**Comment by pmjones** [comment]
@shadowhand @elazar Thoughts on ^^ ?

**Comment by shadowhand** [comment]
Probably best.

**Comment by elazar** [comment]
If the goal is to maintain the independence of the two packages from each other, yeah, I suppose that makes sense. Seems like overkill to have an entirely separate package for a single and fairly small interface, but c'est la vie.

**Comment by pmjones** [comment]
@elazar Yeah I get that. Even so, I don't want people who want the middleware package to _have_ to bring in Relay itself, and vice versa.

So, I'll start a separate Interface package, then. Thanks, folks.

**Comment by pmjones** [comment]
All right, in the interim before creating the separate interface package and finalizing on 2.0, I think it's useful to tag a 1.0 release of Middleware as it is now. Objections?

**Comment by shadowhand** [comment]
Yes please.

**Comment by pmjones** [comment]
Done.

**Comment by pmjones** [comment]
I suppose the thing to do here is wait until the FIG approves (or rejects) an HTTP middleware interface proper.
