### ISSUE TITLE
JsonDecoder has no error checking

### ISSUE THREAD

**Issue by elazar** [relayphp/Relay.Middleware#13]
`JsonDecoder` performs [no error checking](https://github.com/relayphp/Relay.Middleware/blob/b4e09bd21e426732e009d91eb808ef5929af6633/src/JsonDecoder.php#L31-L34) to confirm that the alleged JSON was parsed successfully.

We're currently having to use a different middleware in Spark that [provides this functionality](https://github.com/sparkphp/spark/blob/b4441d7ac6f7a9eaa5fe4ce55b2a7493d82a87bf/src/Handler/JsonContentHandler.php#L25-L29).

Equivalent functionality should be added to `JsonDecoder`, though I'm not entirely certain what the proper response should be. Throwing a exception (e.g. `\DomainException`, `\RuntimeException`)?

**Comment by pmjones** [comment]
I wonder if it would be reasonable to avoid the call to $next and modify the response in-place with an appropriate error code, and return the response right then.

**Comment by elazar** [comment]
My only reservation in doing that is giving the client receiving the response an indication of why the failure occurred. I think the most appropriate response code would be `400 Bad Request`, but that alone isn't very helpful for debugging purposes.

I also don't want to step on the toes of any conventions the Relay user may have in storing error information in the response body. That's why I'm wondering if throwing an exception wouldn't be a better approach.

That said, `ExceptionHandler` [presently assumes](https://github.com/relayphp/Relay.Middleware/blob/b4e09bd21e426732e009d91eb808ef5929af6633/src/ExceptionHandler.php#L22) that any exception thrown implies a `500 Internal Server Error` response, which isn't conducive to using the exception approach to resolve this issue.

**Comment by elazar** [comment]
For context, here's a bit more about what we're using in Spark: [`ContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/ContentHandler.php) provides a base class that's extended by [`FormContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/FormContentHandler.php) and [`JsonContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/JsonContentHandler.php). This setup makes it easy to create a new middleware to support a different content type.

**Comment by pmjones** [comment]
Perhaps we want to add an HttpStatusException, where the exception code the HTTP status code, and the exception message is the message that goes into the response body?

**Comment by elazar** [comment]
That seems reasonable.

**Comment by shadowhand** [comment]
@pmjones see the referenced issue above... would you be interested in us contributing our content handlers to Relay? This currently covers: 
- [`ContentHandler`](https://github.com/sparkphp/spark/blob/522447c12c52ed2ef0a546c9aca77cc5e79487aa/src/Handler/ContentHandler.php) an abstract base class for content handling
- [`FormContentHandler`](https://github.com/sparkphp/spark/blob/522447c12c52ed2ef0a546c9aca77cc5e79487aa/src/Handler/FormContentHandler.php) for handling of form data
- [`JsonContentHandler`](https://github.com/sparkphp/spark/blob/522447c12c52ed2ef0a546c9aca77cc5e79487aa/src/Handler/JsonContentHandler.php) for handling of JSON

**Comment by pmjones** [comment]
I would!

**Comment by shadowhand** [comment]
@pmjones ^ PR created.

**Comment by shadowhand** [comment]
I think this can be closed by #14.

**Comment by pmjones** [comment]
Thanks @shadowhand
