### ISSUE TITLE
phpunit requirement is missing

### ISSUE THREAD

**Issue by shadowhand** [relayphp/Relay.Middleware#15]
(Creating this issue because I think it should be documented.)

b4578bbfd8f7d085aa628a527fc70a3ccd0a02ac removed `phpunit` which is required to run unit tests. Further discussion can be seen at https://github.com/relayphp/Relay.Middleware/pull/14#issuecomment-161380430

Personally I don't think it is fair to developers to force them to use your workflow. Having globally installed phpunit does not protect against version differences and does not allow packages to be tested in isolation.

**Comment by pmjones** [comment]
Understood. You may wish to likewise document it in every Aura, Relay, and Radar package as well, since none of them have it either. Oh, and Arbiter.

**Comment by harikt** [comment]
I am neither a fan of including phpunit in the require-dev. It is already a dependency that a user have it. And to those who don't have a huge bandwidth will help it.
