### ISSUE TITLE
Add sanity checks

### ISSUE THREAD

**Issue by mindplay-dk** [relayphp/Relay.Middleware#18]
You should add `ini_get` and `throw` statements to a constructor in `SessionHeadersHandler` for the conditions described in the doc-block, so that the component will fail early under conditions which might cause it to silently malfunction at a later time.

**Comment by pmjones** [comment]
Good call. If you have the time and inclination to submit a PR that adds the checks (and perhaps throw an exception if they fail) then I can merge it so you get credit; otherwise I'll go after it myself at some point. Thanks!

**Comment by mindplay-dk** [comment]
I can't, I'm sorry - doing about 3 too many projects at the same time ;-)

**Comment by pmjones** [comment]
I have a similar problem; I'll get to it later myself, then. Thanks again!

**Comment by pmjones** [comment]
Done. Thanks!
