### ISSUE TITLE
zendframework/zend-diactoros has been abandoned

### ISSUE THREAD

**Issue by cxj** [relayphp/Relay.Middleware#28]
`require-dev` dependency `zendframework/zend-diactoros` has been abandoned. The recommended replacement is `laminas/laminas-diactoros`.  Note that the replacement requires PHP 7.1 or later.

**Comment by kevinsmith** [comment]
Thanks for bringing this to my attention, @cxj. Given this project's age, growing incompatibilities, and the lack of meaningful ongoing development, I'm actually going to archive it and mark its package abandoned as well.
