### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by shadowhand** [relayphp/Relay.Middleware#4]
There are currently no tags for `relay/middleware` which means that we cannot lock in a version and drop the `minimum-stability: dev` flag from our projects. All of the other ADR packages (relay, arbiter, etc) have tags, this is the only project without.

Thanks!

**Comment by pmjones** [comment]
Good call. Coming up soon.

**Comment by pmjones** [comment]
Done! https://github.com/relayphp/Relay.Middleware/releases

**Comment by shadowhand** [comment]
:+1: thanks!
